id: AF49CF386
title: Prayer for the Long Life of Lochen Ngawang Chöpal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:38:51.413056
  last_modified_at: 2022-03-01 00:38:51.413066
